// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Zora from "zora";
import * as Arrays from "../../../src/Arrays.mjs";
import * as Js_dict from "rescript/lib/es6/js_dict.js";

function testEqual(t, name, lhs, rhs) {
  t.test(name, (async function (t) {
          t.equal(lhs, rhs, name);
        }));
}

Zora.test("array of strings", (function (t) {
        var data = [
          "first",
          "second",
          "third",
          "fourth",
          "fifth"
        ];
        var json = [
          "first",
          "second",
          "third",
          "fourth",
          "fifth"
        ];
        var encoded = Arrays.stringArray_encode(data);
        testEqual(t, "encode string array", encoded, json);
        var decoded = Arrays.stringArray_decode(json);
        testEqual(t, "decode string array preserves order", decoded, {
              TAG: "Ok",
              _0: data
            });
      }));

Zora.test("array of ints", (function (t) {
        var data = [
          1,
          2,
          3,
          4,
          5
        ];
        var json = [
          1.0,
          2.0,
          3.0,
          4.0,
          5.0
        ];
        var encoded = Arrays.intArray_encode(data);
        testEqual(t, "encode int array", encoded, json);
        var decoded = Arrays.intArray_decode(json);
        testEqual(t, "decode int array preserves order", decoded, {
              TAG: "Ok",
              _0: data
            });
      }));

Zora.test("array of floats", (function (t) {
        var data = [
          1.1,
          2.2,
          3.3,
          4.4,
          5.5
        ];
        var json = [
          1.1,
          2.2,
          3.3,
          4.4,
          5.5
        ];
        var encoded = Arrays.floatArray_encode(data);
        testEqual(t, "encode float array", encoded, json);
        var decoded = Arrays.floatArray_decode(json);
        testEqual(t, "decode float array preserves order", decoded, {
              TAG: "Ok",
              _0: data
            });
      }));

Zora.test("array of bools", (function (t) {
        var data = [
          true,
          false,
          true,
          false,
          true
        ];
        var json = [
          true,
          false,
          true,
          false,
          true
        ];
        var encoded = Arrays.boolArray_encode(data);
        testEqual(t, "encode bool array", encoded, json);
        var decoded = Arrays.boolArray_decode(json);
        testEqual(t, "decode bool array preserves order", decoded, {
              TAG: "Ok",
              _0: data
            });
      }));

Zora.test("array of records", (function (t) {
        var data = [
          {
            id: 1,
            name: "first"
          },
          {
            id: 2,
            name: "second"
          },
          {
            id: 3,
            name: "third"
          }
        ];
        var json = [
          Js_dict.fromArray([
                [
                  "id",
                  1.0
                ],
                [
                  "name",
                  "first"
                ]
              ]),
          Js_dict.fromArray([
                [
                  "id",
                  2.0
                ],
                [
                  "name",
                  "second"
                ]
              ]),
          Js_dict.fromArray([
                [
                  "id",
                  3.0
                ],
                [
                  "name",
                  "third"
                ]
              ])
        ];
        var encoded = Arrays.recordArray_encode(data);
        testEqual(t, "encode record array", encoded, json);
        var decoded = Arrays.recordArray_decode(json);
        testEqual(t, "decode record array preserves order", decoded, {
              TAG: "Ok",
              _0: data
            });
      }));

Zora.test("nested arrays", (function (t) {
        var data = [
          [
            1,
            2
          ],
          [
            3,
            4
          ],
          [
            5,
            6
          ]
        ];
        var json = [
          [
            1.0,
            2.0
          ],
          [
            3.0,
            4.0
          ],
          [
            5.0,
            6.0
          ]
        ];
        var encoded = Arrays.nestedArray_encode(data);
        testEqual(t, "encode nested array", encoded, json);
        var decoded = Arrays.nestedArray_decode(json);
        testEqual(t, "decode nested array preserves order", decoded, {
              TAG: "Ok",
              _0: data
            });
      }));

Zora.test("empty array", (function (t) {
        var data = [];
        var json = [];
        var encoded = Arrays.stringArray_encode(data);
        testEqual(t, "encode empty array", encoded, json);
        var decoded = Arrays.stringArray_decode(json);
        testEqual(t, "decode empty array", decoded, {
              TAG: "Ok",
              _0: data
            });
      }));

Zora.test("single element array", (function (t) {
        var data = ["only"];
        var json = ["only"];
        var encoded = Arrays.stringArray_encode(data);
        testEqual(t, "encode single element array", encoded, json);
        var decoded = Arrays.stringArray_decode(json);
        testEqual(t, "decode single element array", decoded, {
              TAG: "Ok",
              _0: data
            });
      }));

export {
  testEqual ,
}
/*  Not a pure module */
