// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Zora from "zora";
import * as Options from "../../../src/Options.mjs";

function testEqual(t, name, lhs, rhs) {
  t.test(name, (async function (t) {
          t.equal(lhs, rhs, name);
        }));
}

Zora.test("top-level option", (function (t) {
        testEqual(t, "encode None", Options.topLevel_encode(undefined), null);
        testEqual(t, "encode Some", Options.topLevel_encode(1), 1);
        testEqual(t, "decode null", Options.topLevel_decode(null), {
              TAG: "Ok",
              _0: undefined
            });
        testEqual(t, "decode value", Options.topLevel_decode(1), {
              TAG: "Ok",
              _0: 1
            });
      }));

Zora.test("option in array", (function (t) {
        var json = [
          1,
          null
        ];
        testEqual(t, "encode", Options.inArray_encode([
                  1,
                  undefined
                ]), json);
        testEqual(t, "decode", Options.inArray_decode(json), {
              TAG: "Ok",
              _0: [
                1,
                undefined
              ]
            });
      }));

Zora.test("option in tuple", (function (t) {
        var json = [
          null,
          "a"
        ];
        testEqual(t, "encode", Options.inTuple_encode([
                  undefined,
                  "a"
                ]), json);
        testEqual(t, "decode", Options.inTuple_decode(json), {
              TAG: "Ok",
              _0: [
                undefined,
                "a"
              ]
            });
      }));

Zora.test("option in variant", (function (t) {
        var json = [
          "Wrap",
          null
        ];
        testEqual(t, "encode", Options.inVariant_encode({
                  TAG: "Wrap",
                  _0: undefined
                }), json);
        testEqual(t, "decode", Options.inVariant_decode(json), {
              TAG: "Ok",
              _0: {
                TAG: "Wrap",
                _0: undefined
              }
            });
      }));

export {
  testEqual ,
}
/*  Not a pure module */
