// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Zora from "zora";
import * as Polyvariants from "../../../src/Polyvariants.mjs";

function testEqual(t, name, lhs, rhs) {
  t.test(name, (async function (t) {
          t.equal(lhs, rhs, name);
        }));
}

Zora.test("polymorphic variants with attribute", (function (t) {
        var polyvariantEncoded = Polyvariants.t_encode("one");
        testEqual(t, "encode 하나", polyvariantEncoded, "하나");
        var polyvariantEncoded$1 = Polyvariants.t_encode("two");
        testEqual(t, "encode 둘", polyvariantEncoded$1, "둘");
        var polyvariantDecoded = Polyvariants.t_decode("하나");
        testEqual(t, "decode 하나", polyvariantDecoded, {
              TAG: "Ok",
              _0: "one"
            });
        var polyvariantDecoded$1 = Polyvariants.t_decode("둘");
        testEqual(t, "decode 둘", polyvariantDecoded$1, {
              TAG: "Ok",
              _0: "two"
            });
      }));

Zora.test("polymorphic variants", (function (t) {
        var polyvariantEncoded = Polyvariants.t1_encode("one");
        testEqual(t, "encode #one", polyvariantEncoded, ["one"]);
        var polyvariantEncoded$1 = Polyvariants.t1_encode("two");
        testEqual(t, "encode #two", polyvariantEncoded$1, ["two"]);
        var polyvariantDecoded = Polyvariants.t1_decode(["one"]);
        testEqual(t, "decode one", polyvariantDecoded, {
              TAG: "Ok",
              _0: "one"
            });
        var polyvariantDecoded$1 = Polyvariants.t1_decode(["two"]);
        testEqual(t, "decode two", polyvariantDecoded$1, {
              TAG: "Ok",
              _0: "two"
            });
      }));

Zora.test("polymorphic variants with @spice.as number", (function (t) {
        var polyvariantEncoded = Polyvariants.t2_encode("one");
        testEqual(t, "encode 1.0", polyvariantEncoded, 1.0);
        var polyvariantEncoded$1 = Polyvariants.t2_encode("two");
        testEqual(t, "encode 2.0", polyvariantEncoded$1, 2.0);
        var polyvariantDecoded = Polyvariants.t2_decode(1.0);
        testEqual(t, "decode 1.0", polyvariantDecoded, {
              TAG: "Ok",
              _0: "one"
            });
        var polyvariantDecoded$1 = Polyvariants.t2_decode(2.0);
        testEqual(t, "decode 2.0", polyvariantDecoded$1, {
              TAG: "Ok",
              _0: "two"
            });
      }));

Zora.test("polyvariant error path includes correct index", (function (t) {
        var invalidJson = [
          "WithArgs",
          "not an int",
          "valid string"
        ];
        var decoded = Polyvariants.withArgs_decode(invalidJson);
        t.test("error path shows [1] for first argument", (async function (t) {
                if (decoded.TAG === "Ok") {
                  t.fail("expected decode to fail");
                  return ;
                }
                t.equal(decoded._0.path, "[1]", "path should be [1]");
              }));
      }));

Zora.test("generic polyvariant with single type parameter", (function (t) {
        var someEncoded = Polyvariants.t3_string_encode({
              NAME: "Some",
              VAL: "hello"
            });
        testEqual(t, "encode #Some(\"hello\")", someEncoded, [
              "Some",
              "hello"
            ]);
        var noneEncoded = Polyvariants.t3_string_encode("None");
        testEqual(t, "encode #None", noneEncoded, ["None"]);
        var someDecoded = Polyvariants.t3_string_decode([
              "Some",
              "hello"
            ]);
        testEqual(t, "decode #Some", someDecoded, {
              TAG: "Ok",
              _0: {
                NAME: "Some",
                VAL: "hello"
              }
            });
        var noneDecoded = Polyvariants.t3_string_decode(["None"]);
        testEqual(t, "decode #None", noneDecoded, {
              TAG: "Ok",
              _0: "None"
            });
      }));

Zora.test("generic polyvariant with multiple type parameters", (function (t) {
        var leftEncoded = Polyvariants.t4_string_int_encode({
              NAME: "Left",
              VAL: "hello"
            });
        testEqual(t, "encode #Left(\"hello\")", leftEncoded, [
              "Left",
              "hello"
            ]);
        var rightEncoded = Polyvariants.t4_string_int_encode({
              NAME: "Right",
              VAL: 42
            });
        testEqual(t, "encode #Right(42)", rightEncoded, [
              "Right",
              42.0
            ]);
        var bothEncoded = Polyvariants.t4_string_int_encode({
              NAME: "Both",
              VAL: [
                "hello",
                42
              ]
            });
        testEqual(t, "encode #Both(\"hello\", 42)", bothEncoded, [
              "Both",
              "hello",
              42.0
            ]);
        var leftDecoded = Polyvariants.t4_string_int_decode([
              "Left",
              "hello"
            ]);
        testEqual(t, "decode #Left", leftDecoded, {
              TAG: "Ok",
              _0: {
                NAME: "Left",
                VAL: "hello"
              }
            });
        var rightDecoded = Polyvariants.t4_string_int_decode([
              "Right",
              42.0
            ]);
        testEqual(t, "decode #Right", rightDecoded, {
              TAG: "Ok",
              _0: {
                NAME: "Right",
                VAL: 42
              }
            });
        var bothDecoded = Polyvariants.t4_string_int_decode([
              "Both",
              "hello",
              42.0
            ]);
        testEqual(t, "decode #Both", bothDecoded, {
              TAG: "Ok",
              _0: {
                NAME: "Both",
                VAL: [
                  "hello",
                  42
                ]
              }
            });
      }));

export {
  testEqual ,
}
/*  Not a pure module */
