// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Zora from "zora";
import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Records from "../../../src/Records.mjs";

function testEqual(t, name, lhs, rhs) {
  t.test(name, (async function (t) {
          t.equal(lhs, rhs, name);
        }));
}

Zora.test("record with @spice.key", (function (t) {
        var sample = {};
        sample["spice-label"] = "sample";
        sample["spice-value"] = 1.0;
        var sampleRecord = {
          label: "sample",
          value: 1
        };
        var encoded = Records.t_encode(sampleRecord);
        testEqual(t, "encode", encoded, sample);
        var decoded = Records.t_decode(sample);
        testEqual(t, "decode", decoded, {
              TAG: "Ok",
              _0: sampleRecord
            });
      }));

Zora.test("record without @spice.key", (function (t) {
        var sample = {};
        sample["label"] = "sample";
        sample["value"] = 1.0;
        var sampleRecord = {
          label: "sample",
          value: 1
        };
        var encoded = Records.t1_encode(sampleRecord);
        testEqual(t, "encode", encoded, sample);
        var decoded = Records.t1_decode(sample);
        testEqual(t, "decode", decoded, {
              TAG: "Ok",
              _0: sampleRecord
            });
      }));

Zora.test("record with optional field", (function (t) {
        var sample1 = {};
        sample1["label"] = "sample";
        sample1["value"] = 1.0;
        var sampleRecord1 = {
          label: "sample",
          value: 1
        };
        var encoded = Records.tOp_encode(sampleRecord1);
        testEqual(t, "encode", encoded, sample1);
        var decoded = Records.tOp_decode(sample1);
        testEqual(t, "decode", decoded, {
              TAG: "Ok",
              _0: sampleRecord1
            });
        var sample2 = {};
        sample2["label"] = "sample";
        var encoded$1 = Records.tOp_encode({
              label: "sample"
            });
        testEqual(t, "encode omit optional field", encoded$1, sample2);
        var sample3 = {};
        sample3["label"] = null;
        var encoded$2 = Records.tOp_encode({});
        testEqual(t, "encode omit optional field with None field", encoded$2, sample3);
      }));

Zora.test("nested record error path", (function (t) {
        var invalidJson = Js_dict.fromArray([[
                "one",
                Js_dict.fromArray([[
                        "value",
                        "not an int"
                      ]])
              ]]);
        var decoded = Records.outer_decode(invalidJson);
        t.test("error path includes full nested path", (async function (t) {
                if (decoded.TAG === "Ok") {
                  t.fail("expected decode to fail");
                  return ;
                }
                t.equal(decoded._0.path, ".one.value", "path should be .one.value");
              }));
      }));

Zora.test("deeply nested record error path", (function (t) {
        var invalidJson = Js_dict.fromArray([[
                "level1",
                Js_dict.fromArray([[
                        "one",
                        Js_dict.fromArray([[
                                "value",
                                "not an int"
                              ]])
                      ]])
              ]]);
        var decoded = Records.deeplyNested_decode(invalidJson);
        t.test("error path includes deeply nested path", (async function (t) {
                if (decoded.TAG === "Ok") {
                  t.fail("expected decode to fail");
                  return ;
                }
                t.equal(decoded._0.path, ".level1.one.value", "path should be .level1.one.value");
              }));
      }));

Zora.test("record with @spice.default", (function (t) {
        var decoded = Records.withDefault_decode({});
        testEqual(t, "missing fields use defaults", decoded, {
              TAG: "Ok",
              _0: {
                opt: 1,
                num: 0
              }
            });
        var decoded$1 = Records.withDefault_decode(Js_dict.fromArray([
                  [
                    "opt",
                    2
                  ],
                  [
                    "num",
                    3
                  ]
                ]));
        testEqual(t, "present fields override defaults", decoded$1, {
              TAG: "Ok",
              _0: {
                opt: 2,
                num: 3
              }
            });
      }));

Zora.test("generic record with single type parameter", (function (t) {
        var sampleJson = Js_dict.fromArray([[
                "a",
                [
                  "one",
                  "two",
                  "three"
                ]
              ]]);
        var sampleRecord = {
          a: [
            "one",
            "two",
            "three"
          ]
        };
        var encoded = Records.t5_string_encode(sampleRecord);
        testEqual(t, "encode", encoded, sampleJson);
        var decoded = Records.t5_string_decode(sampleJson);
        testEqual(t, "decode", decoded, {
              TAG: "Ok",
              _0: sampleRecord
            });
      }));

Zora.test("generic record with multiple type parameters", (function (t) {
        var sampleJson = Js_dict.fromArray([
              [
                "key",
                "myKey"
              ],
              [
                "value",
                42.0
              ]
            ]);
        var sampleRecord = {
          key: "myKey",
          value: 42
        };
        var encoded = Records.t6_string_int_encode(sampleRecord);
        testEqual(t, "encode", encoded, sampleJson);
        var decoded = Records.t6_string_int_decode(sampleJson);
        testEqual(t, "decode", decoded, {
              TAG: "Ok",
              _0: sampleRecord
            });
      }));

export {
  testEqual ,
}
/*  Not a pure module */
