// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Zora from "zora";
import * as Variants from "../../../src/Variants.mjs";

function testEqual(t, name, lhs, rhs) {
  t.test(name, (async function (t) {
          t.equal(lhs, rhs, name);
        }));
}

Zora.test("variants with @spice.as", (function (t) {
        var variantEncoded = Variants.t_encode("One");
        testEqual(t, "encode 하나", variantEncoded, 1);
        var variantEncoded$1 = Variants.t_encode("Two");
        testEqual(t, "encode 둘", variantEncoded$1, "둘");
        var variantDecoded = Variants.t_decode(1);
        testEqual(t, "decode 하나", variantDecoded, {
              TAG: "Ok",
              _0: "One"
            });
        var variantDecoded$1 = Variants.t_decode("둘");
        testEqual(t, "decode 둘", variantDecoded$1, {
              TAG: "Ok",
              _0: "Two"
            });
      }));

Zora.test("variants without @spice.as", (function (t) {
        var variantEncoded = Variants.t1_encode("One1");
        testEqual(t, "encode One1", variantEncoded, ["One1"]);
        var variantEncoded$1 = Variants.t1_encode("Two1");
        testEqual(t, "encode Two1", variantEncoded$1, ["Two1"]);
        var variantDecoded = Variants.t1_decode(["One1"]);
        testEqual(t, "decode [\"One1\"]", variantDecoded, {
              TAG: "Ok",
              _0: "One1"
            });
        var variantDecoded$1 = Variants.t1_decode(["Two1"]);
        testEqual(t, "decode [\"Two1\"]", variantDecoded$1, {
              TAG: "Ok",
              _0: "Two1"
            });
      }));

Zora.test("unboxed variants with @spice.as", (function (t) {
        var variantEncoded = Variants.t2_encode(0);
        testEqual(t, "encode 하나", variantEncoded, 0.0);
        var variantDecoded = Variants.t2_decode(0.0);
        testEqual(t, "decode 하나", variantDecoded, {
              TAG: "Ok",
              _0: 0
            });
      }));

Zora.test("unboxed variants without @spice.as", (function (t) {
        var variantEncoded = Variants.t3_encode(0);
        testEqual(t, "encode One3(0)", variantEncoded, 0.0);
        var variantDecoded = Variants.t3_decode(0.0);
        testEqual(t, "decode 0", variantDecoded, {
              TAG: "Ok",
              _0: 0
            });
      }));

Zora.test("variants with @spice.as number", (function (t) {
        var variantEncoded = Variants.t4_encode("One");
        testEqual(t, "encode 1.0", variantEncoded, 1.0);
        var variantEncoded$1 = Variants.t4_encode("Two");
        testEqual(t, "encode 2.0", variantEncoded$1, 2.0);
        var variantDecoded = Variants.t4_decode(1.0);
        testEqual(t, "decode 1.0", variantDecoded, {
              TAG: "Ok",
              _0: "One"
            });
        var variantDecoded$1 = Variants.t4_decode(2.0);
        testEqual(t, "decode 2.0", variantDecoded$1, {
              TAG: "Ok",
              _0: "Two"
            });
      }));

Zora.test("variant error path includes correct index", (function (t) {
        var invalidJson = [
          "WithArgs",
          "not an int",
          "valid string"
        ];
        var decoded = Variants.withArgs_decode(invalidJson);
        t.test("error path shows [1] for first argument", (async function (t) {
                if (decoded.TAG === "Ok") {
                  t.fail("expected decode to fail");
                  return ;
                }
                t.equal(decoded._0.path, "[1]", "path should be [1]");
              }));
      }));

Zora.test("generic variant with single type parameter", (function (t) {
        var someEncoded = Variants.t5_string_encode("hello");
        testEqual(t, "encode Some(\"hello\")", someEncoded, [
              "Some",
              "hello"
            ]);
        var noneEncoded = Variants.t5_string_encode(undefined);
        testEqual(t, "encode None", noneEncoded, ["None"]);
        var someDecoded = Variants.t5_string_decode([
              "Some",
              "hello"
            ]);
        testEqual(t, "decode Some", someDecoded, {
              TAG: "Ok",
              _0: "hello"
            });
        var noneDecoded = Variants.t5_string_decode(["None"]);
        testEqual(t, "decode None", noneDecoded, {
              TAG: "Ok",
              _0: undefined
            });
      }));

Zora.test("generic variant with multiple type parameters", (function (t) {
        var leftEncoded = Variants.t6_string_int_encode({
              TAG: "Left",
              _0: "hello"
            });
        testEqual(t, "encode Left(\"hello\")", leftEncoded, [
              "Left",
              "hello"
            ]);
        var rightEncoded = Variants.t6_string_int_encode({
              TAG: "Right",
              _0: 42
            });
        testEqual(t, "encode Right(42)", rightEncoded, [
              "Right",
              42.0
            ]);
        var bothEncoded = Variants.t6_string_int_encode({
              TAG: "Both",
              _0: "hello",
              _1: 42
            });
        testEqual(t, "encode Both(\"hello\", 42)", bothEncoded, [
              "Both",
              "hello",
              42.0
            ]);
        var leftDecoded = Variants.t6_string_int_decode([
              "Left",
              "hello"
            ]);
        testEqual(t, "decode Left", leftDecoded, {
              TAG: "Ok",
              _0: {
                TAG: "Left",
                _0: "hello"
              }
            });
        var rightDecoded = Variants.t6_string_int_decode([
              "Right",
              42.0
            ]);
        testEqual(t, "decode Right", rightDecoded, {
              TAG: "Ok",
              _0: {
                TAG: "Right",
                _0: 42
              }
            });
        var bothDecoded = Variants.t6_string_int_decode([
              "Both",
              "hello",
              42.0
            ]);
        testEqual(t, "decode Both", bothDecoded, {
              TAG: "Ok",
              _0: {
                TAG: "Both",
                _0: "hello",
                _1: 42
              }
            });
      }));

export {
  testEqual ,
}
/*  Not a pure module */
