// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Spice from "./Spice.mjs";
import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

function stringArray_encode(v) {
  return Spice.arrayToJson(Spice.stringToJson, v);
}

function stringArray_decode(v) {
  return Spice.arrayFromJson(Spice.stringFromJson, v);
}

function intArray_encode(v) {
  return Spice.arrayToJson(Spice.intToJson, v);
}

function intArray_decode(v) {
  return Spice.arrayFromJson(Spice.intFromJson, v);
}

function floatArray_encode(v) {
  return Spice.arrayToJson(Spice.floatToJson, v);
}

function floatArray_decode(v) {
  return Spice.arrayFromJson(Spice.floatFromJson, v);
}

function boolArray_encode(v) {
  return Spice.arrayToJson(Spice.boolToJson, v);
}

function boolArray_decode(v) {
  return Spice.arrayFromJson(Spice.boolFromJson, v);
}

function recordItem_encode(v) {
  return Js_dict.fromArray(Spice.filterOptional([
                  [
                    "id",
                    false,
                    Spice.intToJson(v.id)
                  ],
                  [
                    "name",
                    false,
                    Spice.stringToJson(v.name)
                  ]
                ]));
}

function recordItem_decode(v) {
  if (!Array.isArray(v) && (v === null || typeof v !== "object") && typeof v !== "number" && typeof v !== "string" && typeof v !== "boolean") {
    return Spice.error(undefined, "Not an object", v);
  }
  if (!(typeof v === "object" && !Array.isArray(v))) {
    return Spice.error(undefined, "Not an object", v);
  }
  var id = Spice.intFromJson(Belt_Option.getWithDefault(Js_dict.get(v, "id"), null));
  if (id.TAG === "Ok") {
    var name = Spice.stringFromJson(Belt_Option.getWithDefault(Js_dict.get(v, "name"), null));
    if (name.TAG === "Ok") {
      return {
              TAG: "Ok",
              _0: {
                id: id._0,
                name: name._0
              }
            };
    }
    var e = name._0;
    return {
            TAG: "Error",
            _0: {
              path: ".name" + e.path,
              message: e.message,
              value: e.value
            }
          };
  }
  var e$1 = id._0;
  return {
          TAG: "Error",
          _0: {
            path: ".id" + e$1.path,
            message: e$1.message,
            value: e$1.value
          }
        };
}

function recordArray_encode(v) {
  return Spice.arrayToJson(recordItem_encode, v);
}

function recordArray_decode(v) {
  return Spice.arrayFromJson(recordItem_decode, v);
}

function nestedArray_encode(v) {
  return Spice.arrayToJson((function (extra) {
                return Spice.arrayToJson(Spice.intToJson, extra);
              }), v);
}

function nestedArray_decode(v) {
  return Spice.arrayFromJson((function (extra) {
                return Spice.arrayFromJson(Spice.intFromJson, extra);
              }), v);
}

export {
  stringArray_encode ,
  stringArray_decode ,
  intArray_encode ,
  intArray_decode ,
  floatArray_encode ,
  floatArray_decode ,
  boolArray_encode ,
  boolArray_decode ,
  recordItem_encode ,
  recordItem_decode ,
  recordArray_encode ,
  recordArray_decode ,
  nestedArray_encode ,
  nestedArray_decode ,
}
/* No side effect */
