// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Spice from "./Spice.mjs";
import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

var Null = {};

function t_encode(v) {
  return Js_dict.fromArray(Spice.filterOptional([[
                    "n",
                    false,
                    (function (extra) {
                          return Spice.nullToJson(Spice.stringToJson, extra);
                        })(v.n)
                  ]]));
}

function t_decode(v) {
  if (!Array.isArray(v) && (v === null || typeof v !== "object") && typeof v !== "number" && typeof v !== "string" && typeof v !== "boolean") {
    return Spice.error(undefined, "Not an object", v);
  }
  if (!(typeof v === "object" && !Array.isArray(v))) {
    return Spice.error(undefined, "Not an object", v);
  }
  var n = (function (extra) {
        return Spice.nullFromJson(Spice.stringFromJson, extra);
      })(Belt_Option.getWithDefault(Js_dict.get(v, "n"), null));
  if (n.TAG === "Ok") {
    return {
            TAG: "Ok",
            _0: {
              n: n._0
            }
          };
  }
  var e = n._0;
  return {
          TAG: "Error",
          _0: {
            path: ".n" + e.path,
            message: e.message,
            value: e.value
          }
        };
}

export {
  Null ,
  t_encode ,
  t_decode ,
}
/* No side effect */
