// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Spice from "./Spice.mjs";

function t_encode(v) {
  return "m³";
}

function t_decode(v) {
  if (!Array.isArray(v) && (v === null || typeof v !== "object") && typeof v !== "number" && typeof v !== "string" && typeof v !== "boolean") {
    return Spice.error(undefined, "Not a JSONString", v);
  }
  switch (typeof v) {
    case "string" :
        if ("m³" === v) {
          return {
                  TAG: "Ok",
                  _0: "M3"
                };
        } else {
          return Spice.error(undefined, "Not matched", v);
        }
    case "number" :
        return Spice.error(undefined, "Not matched", v);
    default:
      return Spice.error(undefined, "Not a JSONString", v);
  }
}

var Action = {};

export {
  t_encode ,
  t_decode ,
  Action ,
}
/* No side effect */
