// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Spice from "./Spice.mjs";
import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

function t_encode(v) {
  return Js_dict.fromArray(Spice.filterOptional([
                  [
                    "f1",
                    false,
                    (function (extra) {
                          return Spice.optionToJson(Spice.stringToJson, extra);
                        })(v.f1)
                  ],
                  [
                    "f2",
                    false,
                    (function (extra) {
                          return Spice.optionToJson(Spice.stringToJson, extra);
                        })(v.f2)
                  ],
                  [
                    "f3",
                    false,
                    (function (extra) {
                          return Spice.optionToJson(Spice.stringToJson, extra);
                        })(v.f3)
                  ],
                  [
                    "f4",
                    false,
                    (function (extra) {
                          return Spice.optionToJson(Spice.stringToJson, extra);
                        })(v.f4)
                  ],
                  [
                    "f5",
                    false,
                    (function (extra) {
                          return Spice.optionToJson(Spice.stringToJson, extra);
                        })(v.f5)
                  ],
                  [
                    "f6",
                    false,
                    (function (extra) {
                          return Spice.optionToJson(Spice.stringToJson, extra);
                        })(v.f6)
                  ],
                  [
                    "f7",
                    false,
                    (function (extra) {
                          return Spice.optionToJson(Spice.stringToJson, extra);
                        })(v.f7)
                  ],
                  [
                    "f8",
                    false,
                    (function (extra) {
                          return Spice.optionToJson(Spice.stringToJson, extra);
                        })(v.f8)
                  ],
                  [
                    "f9",
                    false,
                    (function (extra) {
                          return Spice.optionToJson(Spice.stringToJson, extra);
                        })(v.f9)
                  ],
                  [
                    "f10",
                    false,
                    (function (extra) {
                          return Spice.optionToJson(Spice.stringToJson, extra);
                        })(v.f10)
                  ],
                  [
                    "f11",
                    false,
                    (function (extra) {
                          return Spice.optionToJson(Spice.stringToJson, extra);
                        })(v.f11)
                  ],
                  [
                    "f12",
                    false,
                    (function (extra) {
                          return Spice.optionToJson(Spice.stringToJson, extra);
                        })(v.f12)
                  ],
                  [
                    "f13",
                    false,
                    (function (extra) {
                          return Spice.optionToJson(Spice.stringToJson, extra);
                        })(v.f13)
                  ],
                  [
                    "f14",
                    false,
                    (function (extra) {
                          return Spice.optionToJson(Spice.stringToJson, extra);
                        })(v.f14)
                  ],
                  [
                    "f15",
                    false,
                    (function (extra) {
                          return Spice.optionToJson(Spice.stringToJson, extra);
                        })(v.f15)
                  ],
                  [
                    "f16",
                    false,
                    (function (extra) {
                          return Spice.optionToJson(Spice.stringToJson, extra);
                        })(v.f16)
                  ],
                  [
                    "f17",
                    false,
                    (function (extra) {
                          return Spice.optionToJson(Spice.stringToJson, extra);
                        })(v.f17)
                  ],
                  [
                    "f18",
                    false,
                    (function (extra) {
                          return Spice.optionToJson(Spice.stringToJson, extra);
                        })(v.f18)
                  ],
                  [
                    "f19",
                    false,
                    (function (extra) {
                          return Spice.optionToJson(Spice.stringToJson, extra);
                        })(v.f19)
                  ],
                  [
                    "f20",
                    false,
                    (function (extra) {
                          return Spice.optionToJson(Spice.stringToJson, extra);
                        })(v.f20)
                  ],
                  [
                    "f21",
                    false,
                    (function (extra) {
                          return Spice.optionToJson(Spice.stringToJson, extra);
                        })(v.f21)
                  ],
                  [
                    "f22",
                    false,
                    (function (extra) {
                          return Spice.optionToJson(Spice.stringToJson, extra);
                        })(v.f22)
                  ],
                  [
                    "f23",
                    false,
                    (function (extra) {
                          return Spice.optionToJson(Spice.stringToJson, extra);
                        })(v.f23)
                  ],
                  [
                    "f24",
                    false,
                    (function (extra) {
                          return Spice.optionToJson(Spice.stringToJson, extra);
                        })(v.f24)
                  ],
                  [
                    "f25",
                    false,
                    (function (extra) {
                          return Spice.optionToJson(Spice.stringToJson, extra);
                        })(v.f25)
                  ],
                  [
                    "f26",
                    false,
                    (function (extra) {
                          return Spice.optionToJson(Spice.stringToJson, extra);
                        })(v.f26)
                  ]
                ]));
}

function t_decode(v) {
  if (!Array.isArray(v) && (v === null || typeof v !== "object") && typeof v !== "number" && typeof v !== "string" && typeof v !== "boolean") {
    return Spice.error(undefined, "Not an object", v);
  }
  if (!(typeof v === "object" && !Array.isArray(v))) {
    return Spice.error(undefined, "Not an object", v);
  }
  var f1 = (function (extra) {
        return Spice.optionFromJson(Spice.stringFromJson, extra);
      })(Belt_Option.getWithDefault(Js_dict.get(v, "f1"), null));
  if (f1.TAG === "Ok") {
    var f2 = (function (extra) {
          return Spice.optionFromJson(Spice.stringFromJson, extra);
        })(Belt_Option.getWithDefault(Js_dict.get(v, "f2"), null));
    if (f2.TAG === "Ok") {
      var f3 = (function (extra) {
            return Spice.optionFromJson(Spice.stringFromJson, extra);
          })(Belt_Option.getWithDefault(Js_dict.get(v, "f3"), null));
      if (f3.TAG === "Ok") {
        var f4 = (function (extra) {
              return Spice.optionFromJson(Spice.stringFromJson, extra);
            })(Belt_Option.getWithDefault(Js_dict.get(v, "f4"), null));
        if (f4.TAG === "Ok") {
          var f5 = (function (extra) {
                return Spice.optionFromJson(Spice.stringFromJson, extra);
              })(Belt_Option.getWithDefault(Js_dict.get(v, "f5"), null));
          if (f5.TAG === "Ok") {
            var f6 = (function (extra) {
                  return Spice.optionFromJson(Spice.stringFromJson, extra);
                })(Belt_Option.getWithDefault(Js_dict.get(v, "f6"), null));
            if (f6.TAG === "Ok") {
              var f7 = (function (extra) {
                    return Spice.optionFromJson(Spice.stringFromJson, extra);
                  })(Belt_Option.getWithDefault(Js_dict.get(v, "f7"), null));
              if (f7.TAG === "Ok") {
                var f8 = (function (extra) {
                      return Spice.optionFromJson(Spice.stringFromJson, extra);
                    })(Belt_Option.getWithDefault(Js_dict.get(v, "f8"), null));
                if (f8.TAG === "Ok") {
                  var f9 = (function (extra) {
                        return Spice.optionFromJson(Spice.stringFromJson, extra);
                      })(Belt_Option.getWithDefault(Js_dict.get(v, "f9"), null));
                  if (f9.TAG === "Ok") {
                    var f10 = (function (extra) {
                          return Spice.optionFromJson(Spice.stringFromJson, extra);
                        })(Belt_Option.getWithDefault(Js_dict.get(v, "f10"), null));
                    if (f10.TAG === "Ok") {
                      var f11 = (function (extra) {
                            return Spice.optionFromJson(Spice.stringFromJson, extra);
                          })(Belt_Option.getWithDefault(Js_dict.get(v, "f11"), null));
                      if (f11.TAG === "Ok") {
                        var f12 = (function (extra) {
                              return Spice.optionFromJson(Spice.stringFromJson, extra);
                            })(Belt_Option.getWithDefault(Js_dict.get(v, "f12"), null));
                        if (f12.TAG === "Ok") {
                          var f13 = (function (extra) {
                                return Spice.optionFromJson(Spice.stringFromJson, extra);
                              })(Belt_Option.getWithDefault(Js_dict.get(v, "f13"), null));
                          if (f13.TAG === "Ok") {
                            var f14 = (function (extra) {
                                  return Spice.optionFromJson(Spice.stringFromJson, extra);
                                })(Belt_Option.getWithDefault(Js_dict.get(v, "f14"), null));
                            if (f14.TAG === "Ok") {
                              var f15 = (function (extra) {
                                    return Spice.optionFromJson(Spice.stringFromJson, extra);
                                  })(Belt_Option.getWithDefault(Js_dict.get(v, "f15"), null));
                              if (f15.TAG === "Ok") {
                                var f16 = (function (extra) {
                                      return Spice.optionFromJson(Spice.stringFromJson, extra);
                                    })(Belt_Option.getWithDefault(Js_dict.get(v, "f16"), null));
                                if (f16.TAG === "Ok") {
                                  var f17 = (function (extra) {
                                        return Spice.optionFromJson(Spice.stringFromJson, extra);
                                      })(Belt_Option.getWithDefault(Js_dict.get(v, "f17"), null));
                                  if (f17.TAG === "Ok") {
                                    var f18 = (function (extra) {
                                          return Spice.optionFromJson(Spice.stringFromJson, extra);
                                        })(Belt_Option.getWithDefault(Js_dict.get(v, "f18"), null));
                                    if (f18.TAG === "Ok") {
                                      var f19 = (function (extra) {
                                            return Spice.optionFromJson(Spice.stringFromJson, extra);
                                          })(Belt_Option.getWithDefault(Js_dict.get(v, "f19"), null));
                                      if (f19.TAG === "Ok") {
                                        var f20 = (function (extra) {
                                              return Spice.optionFromJson(Spice.stringFromJson, extra);
                                            })(Belt_Option.getWithDefault(Js_dict.get(v, "f20"), null));
                                        if (f20.TAG === "Ok") {
                                          var f21 = (function (extra) {
                                                return Spice.optionFromJson(Spice.stringFromJson, extra);
                                              })(Belt_Option.getWithDefault(Js_dict.get(v, "f21"), null));
                                          if (f21.TAG === "Ok") {
                                            var f22 = (function (extra) {
                                                  return Spice.optionFromJson(Spice.stringFromJson, extra);
                                                })(Belt_Option.getWithDefault(Js_dict.get(v, "f22"), null));
                                            if (f22.TAG === "Ok") {
                                              var f23 = (function (extra) {
                                                    return Spice.optionFromJson(Spice.stringFromJson, extra);
                                                  })(Belt_Option.getWithDefault(Js_dict.get(v, "f23"), null));
                                              if (f23.TAG === "Ok") {
                                                var f24 = (function (extra) {
                                                      return Spice.optionFromJson(Spice.stringFromJson, extra);
                                                    })(Belt_Option.getWithDefault(Js_dict.get(v, "f24"), null));
                                                if (f24.TAG === "Ok") {
                                                  var f25 = (function (extra) {
                                                        return Spice.optionFromJson(Spice.stringFromJson, extra);
                                                      })(Belt_Option.getWithDefault(Js_dict.get(v, "f25"), null));
                                                  if (f25.TAG === "Ok") {
                                                    var f26 = (function (extra) {
                                                          return Spice.optionFromJson(Spice.stringFromJson, extra);
                                                        })(Belt_Option.getWithDefault(Js_dict.get(v, "f26"), null));
                                                    if (f26.TAG === "Ok") {
                                                      return {
                                                              TAG: "Ok",
                                                              _0: {
                                                                f1: f1._0,
                                                                f2: f2._0,
                                                                f3: f3._0,
                                                                f4: f4._0,
                                                                f5: f5._0,
                                                                f6: f6._0,
                                                                f7: f7._0,
                                                                f8: f8._0,
                                                                f9: f9._0,
                                                                f10: f10._0,
                                                                f11: f11._0,
                                                                f12: f12._0,
                                                                f13: f13._0,
                                                                f14: f14._0,
                                                                f15: f15._0,
                                                                f16: f16._0,
                                                                f17: f17._0,
                                                                f18: f18._0,
                                                                f19: f19._0,
                                                                f20: f20._0,
                                                                f21: f21._0,
                                                                f22: f22._0,
                                                                f23: f23._0,
                                                                f24: f24._0,
                                                                f25: f25._0,
                                                                f26: f26._0
                                                              }
                                                            };
                                                    }
                                                    var e = f26._0;
                                                    return {
                                                            TAG: "Error",
                                                            _0: {
                                                              path: ".f26" + e.path,
                                                              message: e.message,
                                                              value: e.value
                                                            }
                                                          };
                                                  }
                                                  var e$1 = f25._0;
                                                  return {
                                                          TAG: "Error",
                                                          _0: {
                                                            path: ".f25" + e$1.path,
                                                            message: e$1.message,
                                                            value: e$1.value
                                                          }
                                                        };
                                                }
                                                var e$2 = f24._0;
                                                return {
                                                        TAG: "Error",
                                                        _0: {
                                                          path: ".f24" + e$2.path,
                                                          message: e$2.message,
                                                          value: e$2.value
                                                        }
                                                      };
                                              }
                                              var e$3 = f23._0;
                                              return {
                                                      TAG: "Error",
                                                      _0: {
                                                        path: ".f23" + e$3.path,
                                                        message: e$3.message,
                                                        value: e$3.value
                                                      }
                                                    };
                                            }
                                            var e$4 = f22._0;
                                            return {
                                                    TAG: "Error",
                                                    _0: {
                                                      path: ".f22" + e$4.path,
                                                      message: e$4.message,
                                                      value: e$4.value
                                                    }
                                                  };
                                          }
                                          var e$5 = f21._0;
                                          return {
                                                  TAG: "Error",
                                                  _0: {
                                                    path: ".f21" + e$5.path,
                                                    message: e$5.message,
                                                    value: e$5.value
                                                  }
                                                };
                                        }
                                        var e$6 = f20._0;
                                        return {
                                                TAG: "Error",
                                                _0: {
                                                  path: ".f20" + e$6.path,
                                                  message: e$6.message,
                                                  value: e$6.value
                                                }
                                              };
                                      }
                                      var e$7 = f19._0;
                                      return {
                                              TAG: "Error",
                                              _0: {
                                                path: ".f19" + e$7.path,
                                                message: e$7.message,
                                                value: e$7.value
                                              }
                                            };
                                    }
                                    var e$8 = f18._0;
                                    return {
                                            TAG: "Error",
                                            _0: {
                                              path: ".f18" + e$8.path,
                                              message: e$8.message,
                                              value: e$8.value
                                            }
                                          };
                                  }
                                  var e$9 = f17._0;
                                  return {
                                          TAG: "Error",
                                          _0: {
                                            path: ".f17" + e$9.path,
                                            message: e$9.message,
                                            value: e$9.value
                                          }
                                        };
                                }
                                var e$10 = f16._0;
                                return {
                                        TAG: "Error",
                                        _0: {
                                          path: ".f16" + e$10.path,
                                          message: e$10.message,
                                          value: e$10.value
                                        }
                                      };
                              }
                              var e$11 = f15._0;
                              return {
                                      TAG: "Error",
                                      _0: {
                                        path: ".f15" + e$11.path,
                                        message: e$11.message,
                                        value: e$11.value
                                      }
                                    };
                            }
                            var e$12 = f14._0;
                            return {
                                    TAG: "Error",
                                    _0: {
                                      path: ".f14" + e$12.path,
                                      message: e$12.message,
                                      value: e$12.value
                                    }
                                  };
                          }
                          var e$13 = f13._0;
                          return {
                                  TAG: "Error",
                                  _0: {
                                    path: ".f13" + e$13.path,
                                    message: e$13.message,
                                    value: e$13.value
                                  }
                                };
                        }
                        var e$14 = f12._0;
                        return {
                                TAG: "Error",
                                _0: {
                                  path: ".f12" + e$14.path,
                                  message: e$14.message,
                                  value: e$14.value
                                }
                              };
                      }
                      var e$15 = f11._0;
                      return {
                              TAG: "Error",
                              _0: {
                                path: ".f11" + e$15.path,
                                message: e$15.message,
                                value: e$15.value
                              }
                            };
                    }
                    var e$16 = f10._0;
                    return {
                            TAG: "Error",
                            _0: {
                              path: ".f10" + e$16.path,
                              message: e$16.message,
                              value: e$16.value
                            }
                          };
                  }
                  var e$17 = f9._0;
                  return {
                          TAG: "Error",
                          _0: {
                            path: ".f9" + e$17.path,
                            message: e$17.message,
                            value: e$17.value
                          }
                        };
                }
                var e$18 = f8._0;
                return {
                        TAG: "Error",
                        _0: {
                          path: ".f8" + e$18.path,
                          message: e$18.message,
                          value: e$18.value
                        }
                      };
              }
              var e$19 = f7._0;
              return {
                      TAG: "Error",
                      _0: {
                        path: ".f7" + e$19.path,
                        message: e$19.message,
                        value: e$19.value
                      }
                    };
            }
            var e$20 = f6._0;
            return {
                    TAG: "Error",
                    _0: {
                      path: ".f6" + e$20.path,
                      message: e$20.message,
                      value: e$20.value
                    }
                  };
          }
          var e$21 = f5._0;
          return {
                  TAG: "Error",
                  _0: {
                    path: ".f5" + e$21.path,
                    message: e$21.message,
                    value: e$21.value
                  }
                };
        }
        var e$22 = f4._0;
        return {
                TAG: "Error",
                _0: {
                  path: ".f4" + e$22.path,
                  message: e$22.message,
                  value: e$22.value
                }
              };
      }
      var e$23 = f3._0;
      return {
              TAG: "Error",
              _0: {
                path: ".f3" + e$23.path,
                message: e$23.message,
                value: e$23.value
              }
            };
    }
    var e$24 = f2._0;
    return {
            TAG: "Error",
            _0: {
              path: ".f2" + e$24.path,
              message: e$24.message,
              value: e$24.value
            }
          };
  }
  var e$25 = f1._0;
  return {
          TAG: "Error",
          _0: {
            path: ".f1" + e$25.path,
            message: e$25.message,
            value: e$25.value
          }
        };
}

export {
  t_encode ,
  t_decode ,
}
/* No side effect */
