// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Spice from "./Spice.mjs";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";

function topLevel_encode(v) {
  return Spice.optionToJson(Spice.intToJson, v);
}

function topLevel_decode(v) {
  return Spice.optionFromJson(Spice.intFromJson, v);
}

function inArray_encode(v) {
  return Spice.arrayToJson((function (extra) {
                return Spice.optionToJson(Spice.intToJson, extra);
              }), v);
}

function inArray_decode(v) {
  return Spice.arrayFromJson((function (extra) {
                return Spice.optionFromJson(Spice.intFromJson, extra);
              }), v);
}

function inTuple_encode(v) {
  return [
          (function (extra) {
                return Spice.optionToJson(Spice.intToJson, extra);
              })(v[0]),
          Spice.stringToJson(v[1])
        ];
}

function inTuple_decode(v) {
  if (!Array.isArray(v) && (v === null || typeof v !== "object") && typeof v !== "number" && typeof v !== "string" && typeof v !== "boolean") {
    return Spice.error(undefined, "Not a tuple", v);
  }
  if (!Array.isArray(v)) {
    return Spice.error(undefined, "Not a tuple", v);
  }
  if (v.length !== 2) {
    return Spice.error(undefined, "Incorrect cardinality", v);
  }
  var v0 = v[0];
  var v1 = v[1];
  var match = (function (extra) {
        return Spice.optionFromJson(Spice.intFromJson, extra);
      })(v0);
  var match$1 = Spice.stringFromJson(v1);
  if (match.TAG === "Ok") {
    if (match$1.TAG === "Ok") {
      return {
              TAG: "Ok",
              _0: [
                match._0,
                match$1._0
              ]
            };
    }
    var e = match$1._0;
    return {
            TAG: "Error",
            _0: {
              path: "[1]" + e.path,
              message: e.message,
              value: e.value
            }
          };
  }
  var e$1 = match._0;
  return {
          TAG: "Error",
          _0: {
            path: "[0]" + e$1.path,
            message: e$1.message,
            value: e$1.value
          }
        };
}

function inVariant_encode(v) {
  return [
          "Wrap",
          (function (extra) {
                return Spice.optionToJson(Spice.intToJson, extra);
              })(v._0)
        ];
}

function inVariant_decode(v) {
  if (!Array.isArray(v) && (v === null || typeof v !== "object") && typeof v !== "number" && typeof v !== "string" && typeof v !== "boolean") {
    return Spice.error(undefined, "Not a variant", v);
  }
  if (!Array.isArray(v)) {
    return Spice.error(undefined, "Not a variant", v);
  }
  if (v.length === 0) {
    return Spice.error(undefined, "Expected variant, found empty array", v);
  }
  var match = Belt_Array.getExn(v, 0);
  if (!(!Array.isArray(match) && (match === null || typeof match !== "object") && typeof match !== "number" && typeof match !== "string" && typeof match !== "boolean") && typeof match === "string" && match === "Wrap") {
    if (v.length !== 2) {
      return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
    }
    var v0 = (function (extra) {
          return Spice.optionFromJson(Spice.intFromJson, extra);
        })(Belt_Array.getExn(v, 1));
    if (v0.TAG === "Ok") {
      return {
              TAG: "Ok",
              _0: {
                TAG: "Wrap",
                _0: v0._0
              }
            };
    }
    var e = v0._0;
    return {
            TAG: "Error",
            _0: {
              path: "[1]" + e.path,
              message: e.message,
              value: e.value
            }
          };
  }
  return Spice.error(undefined, "Invalid variant constructor", Belt_Array.getExn(v, 0));
}

export {
  topLevel_encode ,
  topLevel_decode ,
  inArray_encode ,
  inArray_decode ,
  inTuple_encode ,
  inTuple_decode ,
  inVariant_encode ,
  inVariant_decode ,
}
/* No side effect */
