// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Spice from "./Spice.mjs";
import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

function t_encode(v) {
  return Js_dict.fromArray(Spice.filterOptional([
                  [
                    "spice-label",
                    false,
                    Spice.stringToJson(v.label)
                  ],
                  [
                    "spice-value",
                    false,
                    Spice.intToJson(v.value)
                  ]
                ]));
}

function t_decode(v) {
  if (!Array.isArray(v) && (v === null || typeof v !== "object") && typeof v !== "number" && typeof v !== "string" && typeof v !== "boolean") {
    return Spice.error(undefined, "Not an object", v);
  }
  if (!(typeof v === "object" && !Array.isArray(v))) {
    return Spice.error(undefined, "Not an object", v);
  }
  var label = Spice.stringFromJson(Belt_Option.getWithDefault(Js_dict.get(v, "spice-label"), null));
  if (label.TAG === "Ok") {
    var value = Spice.intFromJson(Belt_Option.getWithDefault(Js_dict.get(v, "spice-value"), null));
    if (value.TAG === "Ok") {
      return {
              TAG: "Ok",
              _0: {
                label: label._0,
                value: value._0
              }
            };
    }
    var e = value._0;
    return {
            TAG: "Error",
            _0: {
              path: "." + ("spice-value" + e.path),
              message: e.message,
              value: e.value
            }
          };
  }
  var e$1 = label._0;
  return {
          TAG: "Error",
          _0: {
            path: "." + ("spice-label" + e$1.path),
            message: e$1.message,
            value: e$1.value
          }
        };
}

function t1_encode(v) {
  return Js_dict.fromArray(Spice.filterOptional([
                  [
                    "label",
                    false,
                    Spice.stringToJson(v.label)
                  ],
                  [
                    "value",
                    false,
                    Spice.intToJson(v.value)
                  ]
                ]));
}

function t1_decode(v) {
  if (!Array.isArray(v) && (v === null || typeof v !== "object") && typeof v !== "number" && typeof v !== "string" && typeof v !== "boolean") {
    return Spice.error(undefined, "Not an object", v);
  }
  if (!(typeof v === "object" && !Array.isArray(v))) {
    return Spice.error(undefined, "Not an object", v);
  }
  var label = Spice.stringFromJson(Belt_Option.getWithDefault(Js_dict.get(v, "label"), null));
  if (label.TAG === "Ok") {
    var value = Spice.intFromJson(Belt_Option.getWithDefault(Js_dict.get(v, "value"), null));
    if (value.TAG === "Ok") {
      return {
              TAG: "Ok",
              _0: {
                label: label._0,
                value: value._0
              }
            };
    }
    var e = value._0;
    return {
            TAG: "Error",
            _0: {
              path: ".value" + e.path,
              message: e.message,
              value: e.value
            }
          };
  }
  var e$1 = label._0;
  return {
          TAG: "Error",
          _0: {
            path: ".label" + e$1.path,
            message: e$1.message,
            value: e$1.value
          }
        };
}

function tOp_encode(v) {
  return Js_dict.fromArray(Spice.filterOptional([
                  [
                    "label",
                    false,
                    (function (extra) {
                          return Spice.optionToJson(Spice.stringToJson, extra);
                        })(v.label)
                  ],
                  [
                    "value",
                    true,
                    (function (extra) {
                          return Spice.optionToJson(Spice.intToJson, extra);
                        })(v.value)
                  ]
                ]));
}

function tOp_decode(v) {
  if (!Array.isArray(v) && (v === null || typeof v !== "object") && typeof v !== "number" && typeof v !== "string" && typeof v !== "boolean") {
    return Spice.error(undefined, "Not an object", v);
  }
  if (!(typeof v === "object" && !Array.isArray(v))) {
    return Spice.error(undefined, "Not an object", v);
  }
  var label = (function (extra) {
        return Spice.optionFromJson(Spice.stringFromJson, extra);
      })(Belt_Option.getWithDefault(Js_dict.get(v, "label"), null));
  if (label.TAG === "Ok") {
    var value = (function (extra) {
          return Spice.optionFromJson(Spice.intFromJson, extra);
        })(Belt_Option.getWithDefault(Js_dict.get(v, "value"), null));
    if (value.TAG === "Ok") {
      return {
              TAG: "Ok",
              _0: {
                label: label._0,
                value: value._0
              }
            };
    }
    var e = value._0;
    return {
            TAG: "Error",
            _0: {
              path: ".value" + e.path,
              message: e.message,
              value: e.value
            }
          };
  }
  var e$1 = label._0;
  return {
          TAG: "Error",
          _0: {
            path: ".label" + e$1.path,
            message: e$1.message,
            value: e$1.value
          }
        };
}

function inner_decode(v) {
  if (!Array.isArray(v) && (v === null || typeof v !== "object") && typeof v !== "number" && typeof v !== "string" && typeof v !== "boolean") {
    return Spice.error(undefined, "Not an object", v);
  }
  if (!(typeof v === "object" && !Array.isArray(v))) {
    return Spice.error(undefined, "Not an object", v);
  }
  var value = Spice.intFromJson(Belt_Option.getWithDefault(Js_dict.get(v, "value"), null));
  if (value.TAG === "Ok") {
    return {
            TAG: "Ok",
            _0: {
              value: value._0
            }
          };
  }
  var e = value._0;
  return {
          TAG: "Error",
          _0: {
            path: ".value" + e.path,
            message: e.message,
            value: e.value
          }
        };
}

function outer_decode(v) {
  if (!Array.isArray(v) && (v === null || typeof v !== "object") && typeof v !== "number" && typeof v !== "string" && typeof v !== "boolean") {
    return Spice.error(undefined, "Not an object", v);
  }
  if (!(typeof v === "object" && !Array.isArray(v))) {
    return Spice.error(undefined, "Not an object", v);
  }
  var one = inner_decode(Belt_Option.getWithDefault(Js_dict.get(v, "one"), null));
  if (one.TAG === "Ok") {
    return {
            TAG: "Ok",
            _0: {
              one: one._0
            }
          };
  }
  var e = one._0;
  return {
          TAG: "Error",
          _0: {
            path: ".one" + e.path,
            message: e.message,
            value: e.value
          }
        };
}

function deeplyNested_decode(v) {
  if (!Array.isArray(v) && (v === null || typeof v !== "object") && typeof v !== "number" && typeof v !== "string" && typeof v !== "boolean") {
    return Spice.error(undefined, "Not an object", v);
  }
  if (!(typeof v === "object" && !Array.isArray(v))) {
    return Spice.error(undefined, "Not an object", v);
  }
  var level1 = outer_decode(Belt_Option.getWithDefault(Js_dict.get(v, "level1"), null));
  if (level1.TAG === "Ok") {
    return {
            TAG: "Ok",
            _0: {
              level1: level1._0
            }
          };
  }
  var e = level1._0;
  return {
          TAG: "Error",
          _0: {
            path: ".level1" + e.path,
            message: e.message,
            value: e.value
          }
        };
}

function withDefault_encode(v) {
  return Js_dict.fromArray(Spice.filterOptional([
                  [
                    "opt",
                    false,
                    (function (extra) {
                          return Spice.optionToJson(Spice.intToJson, extra);
                        })(v.opt)
                  ],
                  [
                    "num",
                    false,
                    Spice.intToJson(v.num)
                  ]
                ]));
}

function withDefault_decode(v) {
  if (!Array.isArray(v) && (v === null || typeof v !== "object") && typeof v !== "number" && typeof v !== "string" && typeof v !== "boolean") {
    return Spice.error(undefined, "Not an object", v);
  }
  if (!(typeof v === "object" && !Array.isArray(v))) {
    return Spice.error(undefined, "Not an object", v);
  }
  var opt = Belt_Option.getWithDefault(Belt_Option.map(Js_dict.get(v, "opt"), (function (extra) {
              return Spice.optionFromJson(Spice.intFromJson, extra);
            })), {
        TAG: "Ok",
        _0: 1
      });
  if (opt.TAG === "Ok") {
    var num = Belt_Option.getWithDefault(Belt_Option.map(Js_dict.get(v, "num"), Spice.intFromJson), {
          TAG: "Ok",
          _0: 0
        });
    if (num.TAG === "Ok") {
      return {
              TAG: "Ok",
              _0: {
                opt: opt._0,
                num: num._0
              }
            };
    }
    var e = num._0;
    return {
            TAG: "Error",
            _0: {
              path: ".num" + e.path,
              message: e.message,
              value: e.value
            }
          };
  }
  var e$1 = opt._0;
  return {
          TAG: "Error",
          _0: {
            path: ".opt" + e$1.path,
            message: e$1.message,
            value: e$1.value
          }
        };
}

function t5_encode(encoder_data) {
  return function (v) {
    return Js_dict.fromArray(Spice.filterOptional([[
                      "a",
                      false,
                      (function (extra) {
                            return Spice.arrayToJson(encoder_data, extra);
                          })(v.a)
                    ]]));
  };
}

function t5_decode(decoder_data) {
  return function (v) {
    if (!Array.isArray(v) && (v === null || typeof v !== "object") && typeof v !== "number" && typeof v !== "string" && typeof v !== "boolean") {
      return Spice.error(undefined, "Not an object", v);
    }
    if (!(typeof v === "object" && !Array.isArray(v))) {
      return Spice.error(undefined, "Not an object", v);
    }
    var a = (function (extra) {
          return Spice.arrayFromJson(decoder_data, extra);
        })(Belt_Option.getWithDefault(Js_dict.get(v, "a"), null));
    if (a.TAG === "Ok") {
      return {
              TAG: "Ok",
              _0: {
                a: a._0
              }
            };
    }
    var e = a._0;
    return {
            TAG: "Error",
            _0: {
              path: ".a" + e.path,
              message: e.message,
              value: e.value
            }
          };
  };
}

var t5_string_encode = t5_encode(Spice.stringToJson);

var t5_string_decode = t5_decode(Spice.stringFromJson);

function t6_encode(encoder_key, encoder_value) {
  return function (v) {
    return Js_dict.fromArray(Spice.filterOptional([
                    [
                      "key",
                      false,
                      encoder_key(v.key)
                    ],
                    [
                      "value",
                      false,
                      encoder_value(v.value)
                    ]
                  ]));
  };
}

function t6_decode(decoder_key, decoder_value) {
  return function (v) {
    if (!Array.isArray(v) && (v === null || typeof v !== "object") && typeof v !== "number" && typeof v !== "string" && typeof v !== "boolean") {
      return Spice.error(undefined, "Not an object", v);
    }
    if (!(typeof v === "object" && !Array.isArray(v))) {
      return Spice.error(undefined, "Not an object", v);
    }
    var key = decoder_key(Belt_Option.getWithDefault(Js_dict.get(v, "key"), null));
    if (key.TAG === "Ok") {
      var value = decoder_value(Belt_Option.getWithDefault(Js_dict.get(v, "value"), null));
      if (value.TAG === "Ok") {
        return {
                TAG: "Ok",
                _0: {
                  key: key._0,
                  value: value._0
                }
              };
      }
      var e = value._0;
      return {
              TAG: "Error",
              _0: {
                path: ".value" + e.path,
                message: e.message,
                value: e.value
              }
            };
    }
    var e$1 = key._0;
    return {
            TAG: "Error",
            _0: {
              path: ".key" + e$1.path,
              message: e$1.message,
              value: e$1.value
            }
          };
  };
}

var t6_string_int_encode = t6_encode(Spice.stringToJson, Spice.intToJson);

var t6_string_int_decode = t6_decode(Spice.stringFromJson, Spice.intFromJson);

function t7_encode(encoder_a) {
  return function (v) {
    return Js_dict.fromArray(Spice.filterOptional([
                    [
                      "l",
                      false,
                      (function (extra) {
                            return Spice.listToJson(encoder_a, extra);
                          })(v.l)
                    ],
                    [
                      "o",
                      false,
                      (function (extra) {
                            return Spice.optionToJson(encoder_a, extra);
                          })(v.o)
                    ],
                    [
                      "d",
                      false,
                      (function (extra) {
                            return Spice.dictToJson(encoder_a, extra);
                          })(v.d)
                    ],
                    [
                      "r",
                      false,
                      (function (extra) {
                            return Spice.resultToJson(encoder_a, Spice.stringToJson, extra);
                          })(v.r)
                    ]
                  ]));
  };
}

function t7_decode(decoder_a) {
  return function (v) {
    if (!Array.isArray(v) && (v === null || typeof v !== "object") && typeof v !== "number" && typeof v !== "string" && typeof v !== "boolean") {
      return Spice.error(undefined, "Not an object", v);
    }
    if (!(typeof v === "object" && !Array.isArray(v))) {
      return Spice.error(undefined, "Not an object", v);
    }
    var l = (function (extra) {
          return Spice.listFromJson(decoder_a, extra);
        })(Belt_Option.getWithDefault(Js_dict.get(v, "l"), null));
    if (l.TAG === "Ok") {
      var o = (function (extra) {
            return Spice.optionFromJson(decoder_a, extra);
          })(Belt_Option.getWithDefault(Js_dict.get(v, "o"), null));
      if (o.TAG === "Ok") {
        var d = (function (extra) {
              return Spice.dictFromJson(decoder_a, extra);
            })(Belt_Option.getWithDefault(Js_dict.get(v, "d"), null));
        if (d.TAG === "Ok") {
          var r = (function (extra) {
                return Spice.resultFromJson(decoder_a, Spice.stringFromJson, extra);
              })(Belt_Option.getWithDefault(Js_dict.get(v, "r"), null));
          if (r.TAG === "Ok") {
            return {
                    TAG: "Ok",
                    _0: {
                      l: l._0,
                      o: o._0,
                      d: d._0,
                      r: r._0
                    }
                  };
          }
          var e = r._0;
          return {
                  TAG: "Error",
                  _0: {
                    path: ".r" + e.path,
                    message: e.message,
                    value: e.value
                  }
                };
        }
        var e$1 = d._0;
        return {
                TAG: "Error",
                _0: {
                  path: ".d" + e$1.path,
                  message: e$1.message,
                  value: e$1.value
                }
              };
      }
      var e$2 = o._0;
      return {
              TAG: "Error",
              _0: {
                path: ".o" + e$2.path,
                message: e$2.message,
                value: e$2.value
              }
            };
    }
    var e$3 = l._0;
    return {
            TAG: "Error",
            _0: {
              path: ".l" + e$3.path,
              message: e$3.message,
              value: e$3.value
            }
          };
  };
}

function withNull_encode(v) {
  return Js_dict.fromArray(Spice.filterOptional([
                  [
                    "o",
                    false,
                    (function (extra) {
                          return Spice.optionToJson(Spice.stringToJson, extra);
                        })(v.o)
                  ],
                  [
                    "n",
                    false,
                    (function (extra) {
                          return Spice.nullToJson(Spice.stringToJson, extra);
                        })(v.n)
                  ],
                  [
                    "n2",
                    false,
                    (function (extra) {
                          return Spice.nullToJson(Spice.intToJson, extra);
                        })(v.n2)
                  ]
                ]));
}

function withNull_decode(v) {
  if (!Array.isArray(v) && (v === null || typeof v !== "object") && typeof v !== "number" && typeof v !== "string" && typeof v !== "boolean") {
    return Spice.error(undefined, "Not an object", v);
  }
  if (!(typeof v === "object" && !Array.isArray(v))) {
    return Spice.error(undefined, "Not an object", v);
  }
  var o = (function (extra) {
        return Spice.optionFromJson(Spice.stringFromJson, extra);
      })(Belt_Option.getWithDefault(Js_dict.get(v, "o"), null));
  if (o.TAG === "Ok") {
    var n = (function (extra) {
          return Spice.nullFromJson(Spice.stringFromJson, extra);
        })(Belt_Option.getWithDefault(Js_dict.get(v, "n"), null));
    if (n.TAG === "Ok") {
      var n2 = (function (extra) {
            return Spice.nullFromJson(Spice.intFromJson, extra);
          })(Belt_Option.getWithDefault(Js_dict.get(v, "n2"), null));
      if (n2.TAG === "Ok") {
        return {
                TAG: "Ok",
                _0: {
                  o: o._0,
                  n: n._0,
                  n2: n2._0
                }
              };
      }
      var e = n2._0;
      return {
              TAG: "Error",
              _0: {
                path: ".n2" + e.path,
                message: e.message,
                value: e.value
              }
            };
    }
    var e$1 = n._0;
    return {
            TAG: "Error",
            _0: {
              path: ".n" + e$1.path,
              message: e$1.message,
              value: e$1.value
            }
          };
  }
  var e$2 = o._0;
  return {
          TAG: "Error",
          _0: {
            path: ".o" + e$2.path,
            message: e$2.message,
            value: e$2.value
          }
        };
}

export {
  t_encode ,
  t_decode ,
  t1_encode ,
  t1_decode ,
  tOp_encode ,
  tOp_decode ,
  inner_decode ,
  outer_decode ,
  deeplyNested_decode ,
  withDefault_encode ,
  withDefault_decode ,
  t5_encode ,
  t5_decode ,
  t5_string_encode ,
  t5_string_decode ,
  t6_encode ,
  t6_decode ,
  t6_string_int_encode ,
  t6_string_int_decode ,
  t7_encode ,
  t7_decode ,
  withNull_encode ,
  withNull_decode ,
}
/* t5_string_encode Not a pure module */
