// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Spice from "./Spice.mjs";
import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

function params_encode(v) {
  return Js_dict.fromArray(Spice.filterOptional([
                  [
                    "width",
                    true,
                    (function (extra) {
                          return Spice.optionToJson(Spice.floatToJson, extra);
                        })(v.width)
                  ],
                  [
                    "height",
                    true,
                    (function (extra) {
                          return Spice.optionToJson(Spice.floatToJson, extra);
                        })(v.height)
                  ],
                  [
                    "animation",
                    true,
                    (function (extra) {
                          return Spice.optionToJson(Spice.boolToJson, extra);
                        })(v.animation)
                  ],
                  [
                    "focusInput",
                    true,
                    (function (extra) {
                          return Spice.optionToJson(Spice.boolToJson, extra);
                        })(v.focusInput)
                  ],
                  [
                    "autoMapping",
                    true,
                    (function (extra) {
                          return Spice.optionToJson(Spice.boolToJson, extra);
                        })(v.autoMapping)
                  ],
                  [
                    "shorthand",
                    true,
                    (function (extra) {
                          return Spice.optionToJson(Spice.boolToJson, extra);
                        })(v.shorthand)
                  ],
                  [
                    "pleaseReadGuide",
                    true,
                    (function (extra) {
                          return Spice.optionToJson(Spice.intToJson, extra);
                        })(v.pleaseReadGuide)
                  ],
                  [
                    "pleaseReadGuideTimer",
                    true,
                    (function (extra) {
                          return Spice.optionToJson(Spice.floatToJson, extra);
                        })(v.pleaseReadGuideTimer)
                  ],
                  [
                    "maxSuggestItems",
                    true,
                    (function (extra) {
                          return Spice.optionToJson(Spice.intToJson, extra);
                        })(v.maxSuggestItems)
                  ],
                  [
                    "showMoreHName",
                    true,
                    (function (extra) {
                          return Spice.optionToJson(Spice.boolToJson, extra);
                        })(v.showMoreHName)
                  ],
                  [
                    "hideMapBtn",
                    true,
                    (function (extra) {
                          return Spice.optionToJson(Spice.boolToJson, extra);
                        })(v.hideMapBtn)
                  ],
                  [
                    "hideEngBtn",
                    true,
                    (function (extra) {
                          return Spice.optionToJson(Spice.boolToJson, extra);
                        })(v.hideEngBtn)
                  ],
                  [
                    "alwaysShowEngAddr",
                    true,
                    (function (extra) {
                          return Spice.optionToJson(Spice.boolToJson, extra);
                        })(v.alwaysShowEngAddr)
                  ],
                  [
                    "useBannerLink",
                    true,
                    (function (extra) {
                          return Spice.optionToJson(Spice.boolToJson, extra);
                        })(v.useBannerLink)
                  ],
                  [
                    "submitMode",
                    true,
                    (function (extra) {
                          return Spice.optionToJson(Spice.boolToJson, extra);
                        })(v.submitMode)
                  ]
                ]));
}

function params_decode(v) {
  if (!Array.isArray(v) && (v === null || typeof v !== "object") && typeof v !== "number" && typeof v !== "string" && typeof v !== "boolean") {
    return Spice.error(undefined, "Not an object", v);
  }
  if (!(typeof v === "object" && !Array.isArray(v))) {
    return Spice.error(undefined, "Not an object", v);
  }
  var width = (function (extra) {
        return Spice.optionFromJson(Spice.floatFromJson, extra);
      })(Belt_Option.getWithDefault(Js_dict.get(v, "width"), null));
  if (width.TAG === "Ok") {
    var height = (function (extra) {
          return Spice.optionFromJson(Spice.floatFromJson, extra);
        })(Belt_Option.getWithDefault(Js_dict.get(v, "height"), null));
    if (height.TAG === "Ok") {
      var animation = (function (extra) {
            return Spice.optionFromJson(Spice.boolFromJson, extra);
          })(Belt_Option.getWithDefault(Js_dict.get(v, "animation"), null));
      if (animation.TAG === "Ok") {
        var focusInput = (function (extra) {
              return Spice.optionFromJson(Spice.boolFromJson, extra);
            })(Belt_Option.getWithDefault(Js_dict.get(v, "focusInput"), null));
        if (focusInput.TAG === "Ok") {
          var autoMapping = (function (extra) {
                return Spice.optionFromJson(Spice.boolFromJson, extra);
              })(Belt_Option.getWithDefault(Js_dict.get(v, "autoMapping"), null));
          if (autoMapping.TAG === "Ok") {
            var shorthand = (function (extra) {
                  return Spice.optionFromJson(Spice.boolFromJson, extra);
                })(Belt_Option.getWithDefault(Js_dict.get(v, "shorthand"), null));
            if (shorthand.TAG === "Ok") {
              var pleaseReadGuide = (function (extra) {
                    return Spice.optionFromJson(Spice.intFromJson, extra);
                  })(Belt_Option.getWithDefault(Js_dict.get(v, "pleaseReadGuide"), null));
              if (pleaseReadGuide.TAG === "Ok") {
                var pleaseReadGuideTimer = (function (extra) {
                      return Spice.optionFromJson(Spice.floatFromJson, extra);
                    })(Belt_Option.getWithDefault(Js_dict.get(v, "pleaseReadGuideTimer"), null));
                if (pleaseReadGuideTimer.TAG === "Ok") {
                  var maxSuggestItems = (function (extra) {
                        return Spice.optionFromJson(Spice.intFromJson, extra);
                      })(Belt_Option.getWithDefault(Js_dict.get(v, "maxSuggestItems"), null));
                  if (maxSuggestItems.TAG === "Ok") {
                    var showMoreHName = (function (extra) {
                          return Spice.optionFromJson(Spice.boolFromJson, extra);
                        })(Belt_Option.getWithDefault(Js_dict.get(v, "showMoreHName"), null));
                    if (showMoreHName.TAG === "Ok") {
                      var hideMapBtn = (function (extra) {
                            return Spice.optionFromJson(Spice.boolFromJson, extra);
                          })(Belt_Option.getWithDefault(Js_dict.get(v, "hideMapBtn"), null));
                      if (hideMapBtn.TAG === "Ok") {
                        var hideEngBtn = (function (extra) {
                              return Spice.optionFromJson(Spice.boolFromJson, extra);
                            })(Belt_Option.getWithDefault(Js_dict.get(v, "hideEngBtn"), null));
                        if (hideEngBtn.TAG === "Ok") {
                          var alwaysShowEngAddr = (function (extra) {
                                return Spice.optionFromJson(Spice.boolFromJson, extra);
                              })(Belt_Option.getWithDefault(Js_dict.get(v, "alwaysShowEngAddr"), null));
                          if (alwaysShowEngAddr.TAG === "Ok") {
                            var useBannerLink = (function (extra) {
                                  return Spice.optionFromJson(Spice.boolFromJson, extra);
                                })(Belt_Option.getWithDefault(Js_dict.get(v, "useBannerLink"), null));
                            if (useBannerLink.TAG === "Ok") {
                              var submitMode = (function (extra) {
                                    return Spice.optionFromJson(Spice.boolFromJson, extra);
                                  })(Belt_Option.getWithDefault(Js_dict.get(v, "submitMode"), null));
                              if (submitMode.TAG === "Ok") {
                                return {
                                        TAG: "Ok",
                                        _0: {
                                          width: width._0,
                                          height: height._0,
                                          animation: animation._0,
                                          focusInput: focusInput._0,
                                          autoMapping: autoMapping._0,
                                          shorthand: shorthand._0,
                                          pleaseReadGuide: pleaseReadGuide._0,
                                          pleaseReadGuideTimer: pleaseReadGuideTimer._0,
                                          maxSuggestItems: maxSuggestItems._0,
                                          showMoreHName: showMoreHName._0,
                                          hideMapBtn: hideMapBtn._0,
                                          hideEngBtn: hideEngBtn._0,
                                          alwaysShowEngAddr: alwaysShowEngAddr._0,
                                          useBannerLink: useBannerLink._0,
                                          submitMode: submitMode._0
                                        }
                                      };
                              }
                              var e = submitMode._0;
                              return {
                                      TAG: "Error",
                                      _0: {
                                        path: ".submitMode" + e.path,
                                        message: e.message,
                                        value: e.value
                                      }
                                    };
                            }
                            var e$1 = useBannerLink._0;
                            return {
                                    TAG: "Error",
                                    _0: {
                                      path: ".useBannerLink" + e$1.path,
                                      message: e$1.message,
                                      value: e$1.value
                                    }
                                  };
                          }
                          var e$2 = alwaysShowEngAddr._0;
                          return {
                                  TAG: "Error",
                                  _0: {
                                    path: ".alwaysShowEngAddr" + e$2.path,
                                    message: e$2.message,
                                    value: e$2.value
                                  }
                                };
                        }
                        var e$3 = hideEngBtn._0;
                        return {
                                TAG: "Error",
                                _0: {
                                  path: ".hideEngBtn" + e$3.path,
                                  message: e$3.message,
                                  value: e$3.value
                                }
                              };
                      }
                      var e$4 = hideMapBtn._0;
                      return {
                              TAG: "Error",
                              _0: {
                                path: ".hideMapBtn" + e$4.path,
                                message: e$4.message,
                                value: e$4.value
                              }
                            };
                    }
                    var e$5 = showMoreHName._0;
                    return {
                            TAG: "Error",
                            _0: {
                              path: ".showMoreHName" + e$5.path,
                              message: e$5.message,
                              value: e$5.value
                            }
                          };
                  }
                  var e$6 = maxSuggestItems._0;
                  return {
                          TAG: "Error",
                          _0: {
                            path: ".maxSuggestItems" + e$6.path,
                            message: e$6.message,
                            value: e$6.value
                          }
                        };
                }
                var e$7 = pleaseReadGuideTimer._0;
                return {
                        TAG: "Error",
                        _0: {
                          path: ".pleaseReadGuideTimer" + e$7.path,
                          message: e$7.message,
                          value: e$7.value
                        }
                      };
              }
              var e$8 = pleaseReadGuide._0;
              return {
                      TAG: "Error",
                      _0: {
                        path: ".pleaseReadGuide" + e$8.path,
                        message: e$8.message,
                        value: e$8.value
                      }
                    };
            }
            var e$9 = shorthand._0;
            return {
                    TAG: "Error",
                    _0: {
                      path: ".shorthand" + e$9.path,
                      message: e$9.message,
                      value: e$9.value
                    }
                  };
          }
          var e$10 = autoMapping._0;
          return {
                  TAG: "Error",
                  _0: {
                    path: ".autoMapping" + e$10.path,
                    message: e$10.message,
                    value: e$10.value
                  }
                };
        }
        var e$11 = focusInput._0;
        return {
                TAG: "Error",
                _0: {
                  path: ".focusInput" + e$11.path,
                  message: e$11.message,
                  value: e$11.value
                }
              };
      }
      var e$12 = animation._0;
      return {
              TAG: "Error",
              _0: {
                path: ".animation" + e$12.path,
                message: e$12.message,
                value: e$12.value
              }
            };
    }
    var e$13 = height._0;
    return {
            TAG: "Error",
            _0: {
              path: ".height" + e$13.path,
              message: e$13.message,
              value: e$13.value
            }
          };
  }
  var e$14 = width._0;
  return {
          TAG: "Error",
          _0: {
            path: ".width" + e$14.path,
            message: e$14.message,
            value: e$14.value
          }
        };
}

export {
  params_encode ,
  params_decode ,
}
/* No side effect */
