// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Spice from "./Spice.mjs";
import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

function t_encode(v) {
  return Js_dict.fromArray(Spice.filterOptional([[
                    "a",
                    false,
                    Spice.stringToJson(v.a)
                  ]]));
}

function t_decode(v) {
  if (!Array.isArray(v) && (v === null || typeof v !== "object") && typeof v !== "number" && typeof v !== "string" && typeof v !== "boolean") {
    return Spice.error(undefined, "Not an object", v);
  }
  if (!(typeof v === "object" && !Array.isArray(v))) {
    return Spice.error(undefined, "Not an object", v);
  }
  var a = Spice.stringFromJson(Belt_Option.getWithDefault(Js_dict.get(v, "a"), null));
  if (a.TAG === "Ok") {
    return {
            TAG: "Ok",
            _0: {
              a: a._0
            }
          };
  }
  var e = a._0;
  return {
          TAG: "Error",
          _0: {
            path: ".a" + e.path,
            message: e.message,
            value: e.value
          }
        };
}

var M = {
  t_encode: t_encode,
  t_decode: t_decode
};

function response_encode(v) {
  return Js_dict.fromArray(Spice.filterOptional([
                  [
                    "data",
                    false,
                    (function (extra) {
                          return Spice.optionToJson((function (v) {
                                        return v;
                                      }), extra);
                        })(v.data)
                  ],
                  [
                    "errors",
                    false,
                    (function (extra) {
                          return Spice.optionToJson((function (extra) {
                                        return Spice.arrayToJson(t_encode, extra);
                                      }), extra);
                        })(v.errors)
                  ]
                ]));
}

function response_decode(v) {
  if (!Array.isArray(v) && (v === null || typeof v !== "object") && typeof v !== "number" && typeof v !== "string" && typeof v !== "boolean") {
    return Spice.error(undefined, "Not an object", v);
  }
  if (!(typeof v === "object" && !Array.isArray(v))) {
    return Spice.error(undefined, "Not an object", v);
  }
  var data = (function (extra) {
        return Spice.optionFromJson((function (v) {
                      return {
                              TAG: "Ok",
                              _0: v
                            };
                    }), extra);
      })(Belt_Option.getWithDefault(Js_dict.get(v, "data"), null));
  if (data.TAG === "Ok") {
    var errors = (function (extra) {
          return Spice.optionFromJson((function (extra) {
                        return Spice.arrayFromJson(t_decode, extra);
                      }), extra);
        })(Belt_Option.getWithDefault(Js_dict.get(v, "errors"), null));
    if (errors.TAG === "Ok") {
      return {
              TAG: "Ok",
              _0: {
                data: data._0,
                errors: errors._0
              }
            };
    }
    var e = errors._0;
    return {
            TAG: "Error",
            _0: {
              path: ".errors" + e.path,
              message: e.message,
              value: e.value
            }
          };
  }
  var e$1 = data._0;
  return {
          TAG: "Error",
          _0: {
            path: ".data" + e$1.path,
            message: e$1.message,
            value: e$1.value
          }
        };
}

export {
  M ,
  response_encode ,
  response_decode ,
}
/* No side effect */
