// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Spice from "./Spice.mjs";
import * as Js_dict from "@rescript/runtime/lib/es6/Js_dict.js";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";

function params_encode(v) {
  let extra = v.width;
  let extra$1 = v.height;
  let extra$2 = v.animation;
  let extra$3 = v.focusInput;
  let extra$4 = v.autoMapping;
  let extra$5 = v.shorthand;
  let extra$6 = v.pleaseReadGuide;
  let extra$7 = v.pleaseReadGuideTimer;
  let extra$8 = v.maxSuggestItems;
  let extra$9 = v.showMoreHName;
  let extra$10 = v.hideMapBtn;
  let extra$11 = v.hideEngBtn;
  let extra$12 = v.alwaysShowEngAddr;
  let extra$13 = v.useBannerLink;
  let extra$14 = v.submitMode;
  return Js_dict.fromArray(Spice.filterOptional([
    [
      "width",
      Spice.optionToJson(Spice.floatToJson, extra)
    ],
    [
      "height",
      Spice.optionToJson(Spice.floatToJson, extra$1)
    ],
    [
      "animation",
      Spice.optionToJson(Spice.boolToJson, extra$2)
    ],
    [
      "focusInput",
      Spice.optionToJson(Spice.boolToJson, extra$3)
    ],
    [
      "autoMapping",
      Spice.optionToJson(Spice.boolToJson, extra$4)
    ],
    [
      "shorthand",
      Spice.optionToJson(Spice.boolToJson, extra$5)
    ],
    [
      "pleaseReadGuide",
      Spice.optionToJson(Spice.intToJson, extra$6)
    ],
    [
      "pleaseReadGuideTimer",
      Spice.optionToJson(Spice.floatToJson, extra$7)
    ],
    [
      "maxSuggestItems",
      Spice.optionToJson(Spice.intToJson, extra$8)
    ],
    [
      "showMoreHName",
      Spice.optionToJson(Spice.boolToJson, extra$9)
    ],
    [
      "hideMapBtn",
      Spice.optionToJson(Spice.boolToJson, extra$10)
    ],
    [
      "hideEngBtn",
      Spice.optionToJson(Spice.boolToJson, extra$11)
    ],
    [
      "alwaysShowEngAddr",
      Spice.optionToJson(Spice.boolToJson, extra$12)
    ],
    [
      "useBannerLink",
      Spice.optionToJson(Spice.boolToJson, extra$13)
    ],
    [
      "submitMode",
      Spice.optionToJson(Spice.boolToJson, extra$14)
    ]
  ]));
}

function params_decode(v) {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return Spice.error(undefined, "Not an object", v);
  }
  let width = Belt_Option.getWithDefault(Belt_Option.map(Js_dict.get(v, "width"), extra => Spice.optionFromJson(Spice.floatFromJson, extra)), {
    TAG: "Ok",
    _0: undefined
  });
  if (width.TAG === "Ok") {
    let height = Belt_Option.getWithDefault(Belt_Option.map(Js_dict.get(v, "height"), extra => Spice.optionFromJson(Spice.floatFromJson, extra)), {
      TAG: "Ok",
      _0: undefined
    });
    if (height.TAG === "Ok") {
      let animation = Belt_Option.getWithDefault(Belt_Option.map(Js_dict.get(v, "animation"), extra => Spice.optionFromJson(Spice.boolFromJson, extra)), {
        TAG: "Ok",
        _0: undefined
      });
      if (animation.TAG === "Ok") {
        let focusInput = Belt_Option.getWithDefault(Belt_Option.map(Js_dict.get(v, "focusInput"), extra => Spice.optionFromJson(Spice.boolFromJson, extra)), {
          TAG: "Ok",
          _0: undefined
        });
        if (focusInput.TAG === "Ok") {
          let autoMapping = Belt_Option.getWithDefault(Belt_Option.map(Js_dict.get(v, "autoMapping"), extra => Spice.optionFromJson(Spice.boolFromJson, extra)), {
            TAG: "Ok",
            _0: undefined
          });
          if (autoMapping.TAG === "Ok") {
            let shorthand = Belt_Option.getWithDefault(Belt_Option.map(Js_dict.get(v, "shorthand"), extra => Spice.optionFromJson(Spice.boolFromJson, extra)), {
              TAG: "Ok",
              _0: undefined
            });
            if (shorthand.TAG === "Ok") {
              let pleaseReadGuide = Belt_Option.getWithDefault(Belt_Option.map(Js_dict.get(v, "pleaseReadGuide"), extra => Spice.optionFromJson(Spice.intFromJson, extra)), {
                TAG: "Ok",
                _0: undefined
              });
              if (pleaseReadGuide.TAG === "Ok") {
                let pleaseReadGuideTimer = Belt_Option.getWithDefault(Belt_Option.map(Js_dict.get(v, "pleaseReadGuideTimer"), extra => Spice.optionFromJson(Spice.floatFromJson, extra)), {
                  TAG: "Ok",
                  _0: undefined
                });
                if (pleaseReadGuideTimer.TAG === "Ok") {
                  let maxSuggestItems = Belt_Option.getWithDefault(Belt_Option.map(Js_dict.get(v, "maxSuggestItems"), extra => Spice.optionFromJson(Spice.intFromJson, extra)), {
                    TAG: "Ok",
                    _0: undefined
                  });
                  if (maxSuggestItems.TAG === "Ok") {
                    let showMoreHName = Belt_Option.getWithDefault(Belt_Option.map(Js_dict.get(v, "showMoreHName"), extra => Spice.optionFromJson(Spice.boolFromJson, extra)), {
                      TAG: "Ok",
                      _0: undefined
                    });
                    if (showMoreHName.TAG === "Ok") {
                      let hideMapBtn = Belt_Option.getWithDefault(Belt_Option.map(Js_dict.get(v, "hideMapBtn"), extra => Spice.optionFromJson(Spice.boolFromJson, extra)), {
                        TAG: "Ok",
                        _0: undefined
                      });
                      if (hideMapBtn.TAG === "Ok") {
                        let hideEngBtn = Belt_Option.getWithDefault(Belt_Option.map(Js_dict.get(v, "hideEngBtn"), extra => Spice.optionFromJson(Spice.boolFromJson, extra)), {
                          TAG: "Ok",
                          _0: undefined
                        });
                        if (hideEngBtn.TAG === "Ok") {
                          let alwaysShowEngAddr = Belt_Option.getWithDefault(Belt_Option.map(Js_dict.get(v, "alwaysShowEngAddr"), extra => Spice.optionFromJson(Spice.boolFromJson, extra)), {
                            TAG: "Ok",
                            _0: undefined
                          });
                          if (alwaysShowEngAddr.TAG === "Ok") {
                            let useBannerLink = Belt_Option.getWithDefault(Belt_Option.map(Js_dict.get(v, "useBannerLink"), extra => Spice.optionFromJson(Spice.boolFromJson, extra)), {
                              TAG: "Ok",
                              _0: undefined
                            });
                            if (useBannerLink.TAG === "Ok") {
                              let submitMode = Belt_Option.getWithDefault(Belt_Option.map(Js_dict.get(v, "submitMode"), extra => Spice.optionFromJson(Spice.boolFromJson, extra)), {
                                TAG: "Ok",
                                _0: undefined
                              });
                              if (submitMode.TAG === "Ok") {
                                return {
                                  TAG: "Ok",
                                  _0: {
                                    width: width._0,
                                    height: height._0,
                                    animation: animation._0,
                                    focusInput: focusInput._0,
                                    autoMapping: autoMapping._0,
                                    shorthand: shorthand._0,
                                    pleaseReadGuide: pleaseReadGuide._0,
                                    pleaseReadGuideTimer: pleaseReadGuideTimer._0,
                                    maxSuggestItems: maxSuggestItems._0,
                                    showMoreHName: showMoreHName._0,
                                    hideMapBtn: hideMapBtn._0,
                                    hideEngBtn: hideEngBtn._0,
                                    alwaysShowEngAddr: alwaysShowEngAddr._0,
                                    useBannerLink: useBannerLink._0,
                                    submitMode: submitMode._0
                                  }
                                };
                              }
                              let e = submitMode._0;
                              return Spice.error("submitMode", e.message, e.value);
                            }
                            let e$1 = useBannerLink._0;
                            return Spice.error("useBannerLink", e$1.message, e$1.value);
                          }
                          let e$2 = alwaysShowEngAddr._0;
                          return Spice.error("alwaysShowEngAddr", e$2.message, e$2.value);
                        }
                        let e$3 = hideEngBtn._0;
                        return Spice.error("hideEngBtn", e$3.message, e$3.value);
                      }
                      let e$4 = hideMapBtn._0;
                      return Spice.error("hideMapBtn", e$4.message, e$4.value);
                    }
                    let e$5 = showMoreHName._0;
                    return Spice.error("showMoreHName", e$5.message, e$5.value);
                  }
                  let e$6 = maxSuggestItems._0;
                  return Spice.error("maxSuggestItems", e$6.message, e$6.value);
                }
                let e$7 = pleaseReadGuideTimer._0;
                return Spice.error("pleaseReadGuideTimer", e$7.message, e$7.value);
              }
              let e$8 = pleaseReadGuide._0;
              return Spice.error("pleaseReadGuide", e$8.message, e$8.value);
            }
            let e$9 = shorthand._0;
            return Spice.error("shorthand", e$9.message, e$9.value);
          }
          let e$10 = autoMapping._0;
          return Spice.error("autoMapping", e$10.message, e$10.value);
        }
        let e$11 = focusInput._0;
        return Spice.error("focusInput", e$11.message, e$11.value);
      }
      let e$12 = animation._0;
      return Spice.error("animation", e$12.message, e$12.value);
    }
    let e$13 = height._0;
    return Spice.error("height", e$13.message, e$13.value);
  }
  let e$14 = width._0;
  return Spice.error("width", e$14.message, e$14.value);
}

export {
  params_encode,
  params_decode,
}
/* No side effect */
