// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Spice from "./Spice.mjs";
import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

function t_encode(v) {
  return Js_dict.fromArray(Spice.filterOptional([
                  [
                    "spice-label",
                    false,
                    Spice.stringToJson(v.label)
                  ],
                  [
                    "spice-value",
                    false,
                    Spice.intToJson(v.value)
                  ]
                ]));
}

function t_decode(v) {
  if (!Array.isArray(v) && (v === null || typeof v !== "object") && typeof v !== "number" && typeof v !== "string" && typeof v !== "boolean") {
    return Spice.error(undefined, "Not an object", v);
  }
  if (!(typeof v === "object" && !Array.isArray(v))) {
    return Spice.error(undefined, "Not an object", v);
  }
  var label = Spice.stringFromJson(Belt_Option.getWithDefault(Js_dict.get(v, "spice-label"), null));
  if (label.TAG === "Ok") {
    var value = Spice.intFromJson(Belt_Option.getWithDefault(Js_dict.get(v, "spice-value"), null));
    if (value.TAG === "Ok") {
      return {
              TAG: "Ok",
              _0: {
                label: label._0,
                value: value._0
              }
            };
    }
    var e = value._0;
    return {
            TAG: "Error",
            _0: {
              path: "." + ("spice-value" + e.path),
              message: e.message,
              value: e.value
            }
          };
  }
  var e$1 = label._0;
  return {
          TAG: "Error",
          _0: {
            path: "." + ("spice-label" + e$1.path),
            message: e$1.message,
            value: e$1.value
          }
        };
}

function t1_encode(v) {
  return Js_dict.fromArray(Spice.filterOptional([
                  [
                    "label",
                    false,
                    Spice.stringToJson(v.label)
                  ],
                  [
                    "value",
                    false,
                    Spice.intToJson(v.value)
                  ]
                ]));
}

function t1_decode(v) {
  if (!Array.isArray(v) && (v === null || typeof v !== "object") && typeof v !== "number" && typeof v !== "string" && typeof v !== "boolean") {
    return Spice.error(undefined, "Not an object", v);
  }
  if (!(typeof v === "object" && !Array.isArray(v))) {
    return Spice.error(undefined, "Not an object", v);
  }
  var label = Spice.stringFromJson(Belt_Option.getWithDefault(Js_dict.get(v, "label"), null));
  if (label.TAG === "Ok") {
    var value = Spice.intFromJson(Belt_Option.getWithDefault(Js_dict.get(v, "value"), null));
    if (value.TAG === "Ok") {
      return {
              TAG: "Ok",
              _0: {
                label: label._0,
                value: value._0
              }
            };
    }
    var e = value._0;
    return {
            TAG: "Error",
            _0: {
              path: ".value" + e.path,
              message: e.message,
              value: e.value
            }
          };
  }
  var e$1 = label._0;
  return {
          TAG: "Error",
          _0: {
            path: ".label" + e$1.path,
            message: e$1.message,
            value: e$1.value
          }
        };
}

function tOp_encode(v) {
  return Js_dict.fromArray(Spice.filterOptional([
                  [
                    "label",
                    false,
                    (function (extra) {
                          return Spice.optionToJson(Spice.stringToJson, extra);
                        })(v.label)
                  ],
                  [
                    "value",
                    true,
                    (function (extra) {
                          return Spice.optionToJson(Spice.intToJson, extra);
                        })(v.value)
                  ]
                ]));
}

function tOp_decode(v) {
  if (!Array.isArray(v) && (v === null || typeof v !== "object") && typeof v !== "number" && typeof v !== "string" && typeof v !== "boolean") {
    return Spice.error(undefined, "Not an object", v);
  }
  if (!(typeof v === "object" && !Array.isArray(v))) {
    return Spice.error(undefined, "Not an object", v);
  }
  var label = (function (extra) {
        return Spice.optionFromJson(Spice.stringFromJson, extra);
      })(Belt_Option.getWithDefault(Js_dict.get(v, "label"), null));
  if (label.TAG === "Ok") {
    var value = (function (extra) {
          return Spice.optionFromJson(Spice.intFromJson, extra);
        })(Belt_Option.getWithDefault(Js_dict.get(v, "value"), null));
    if (value.TAG === "Ok") {
      return {
              TAG: "Ok",
              _0: {
                label: label._0,
                value: value._0
              }
            };
    }
    var e = value._0;
    return {
            TAG: "Error",
            _0: {
              path: ".value" + e.path,
              message: e.message,
              value: e.value
            }
          };
  }
  var e$1 = label._0;
  return {
          TAG: "Error",
          _0: {
            path: ".label" + e$1.path,
            message: e$1.message,
            value: e$1.value
          }
        };
}

function inner_decode(v) {
  if (!Array.isArray(v) && (v === null || typeof v !== "object") && typeof v !== "number" && typeof v !== "string" && typeof v !== "boolean") {
    return Spice.error(undefined, "Not an object", v);
  }
  if (!(typeof v === "object" && !Array.isArray(v))) {
    return Spice.error(undefined, "Not an object", v);
  }
  var value = Spice.intFromJson(Belt_Option.getWithDefault(Js_dict.get(v, "value"), null));
  if (value.TAG === "Ok") {
    return {
            TAG: "Ok",
            _0: {
              value: value._0
            }
          };
  }
  var e = value._0;
  return {
          TAG: "Error",
          _0: {
            path: ".value" + e.path,
            message: e.message,
            value: e.value
          }
        };
}

function outer_decode(v) {
  if (!Array.isArray(v) && (v === null || typeof v !== "object") && typeof v !== "number" && typeof v !== "string" && typeof v !== "boolean") {
    return Spice.error(undefined, "Not an object", v);
  }
  if (!(typeof v === "object" && !Array.isArray(v))) {
    return Spice.error(undefined, "Not an object", v);
  }
  var one = inner_decode(Belt_Option.getWithDefault(Js_dict.get(v, "one"), null));
  if (one.TAG === "Ok") {
    return {
            TAG: "Ok",
            _0: {
              one: one._0
            }
          };
  }
  var e = one._0;
  return {
          TAG: "Error",
          _0: {
            path: ".one" + e.path,
            message: e.message,
            value: e.value
          }
        };
}

function deeplyNested_decode(v) {
  if (!Array.isArray(v) && (v === null || typeof v !== "object") && typeof v !== "number" && typeof v !== "string" && typeof v !== "boolean") {
    return Spice.error(undefined, "Not an object", v);
  }
  if (!(typeof v === "object" && !Array.isArray(v))) {
    return Spice.error(undefined, "Not an object", v);
  }
  var level1 = outer_decode(Belt_Option.getWithDefault(Js_dict.get(v, "level1"), null));
  if (level1.TAG === "Ok") {
    return {
            TAG: "Ok",
            _0: {
              level1: level1._0
            }
          };
  }
  var e = level1._0;
  return {
          TAG: "Error",
          _0: {
            path: ".level1" + e.path,
            message: e.message,
            value: e.value
          }
        };
}

function withDefault_encode(v) {
  return Js_dict.fromArray(Spice.filterOptional([
                  [
                    "a",
                    false,
                    (function (extra) {
                          return Spice.optionToJson(Spice.intToJson, extra);
                        })(v.a)
                  ],
                  [
                    "b",
                    false,
                    Spice.intToJson(v.b)
                  ]
                ]));
}

function withDefault_decode(v) {
  if (!Array.isArray(v) && (v === null || typeof v !== "object") && typeof v !== "number" && typeof v !== "string" && typeof v !== "boolean") {
    return Spice.error(undefined, "Not an object", v);
  }
  if (!(typeof v === "object" && !Array.isArray(v))) {
    return Spice.error(undefined, "Not an object", v);
  }
  var a = Belt_Option.getWithDefault(Belt_Option.map(Js_dict.get(v, "a"), (function (extra) {
              return Spice.optionFromJson(Spice.intFromJson, extra);
            })), {
        TAG: "Ok",
        _0: 1
      });
  if (a.TAG === "Ok") {
    var b = Belt_Option.getWithDefault(Belt_Option.map(Js_dict.get(v, "b"), Spice.intFromJson), {
          TAG: "Ok",
          _0: 0
        });
    if (b.TAG === "Ok") {
      return {
              TAG: "Ok",
              _0: {
                a: a._0,
                b: b._0
              }
            };
    }
    var e = b._0;
    return {
            TAG: "Error",
            _0: {
              path: ".b" + e.path,
              message: e.message,
              value: e.value
            }
          };
  }
  var e$1 = a._0;
  return {
          TAG: "Error",
          _0: {
            path: ".a" + e$1.path,
            message: e$1.message,
            value: e$1.value
          }
        };
}

export {
  t_encode ,
  t_decode ,
  t1_encode ,
  t1_decode ,
  tOp_encode ,
  tOp_decode ,
  inner_decode ,
  outer_decode ,
  deeplyNested_decode ,
  withDefault_encode ,
  withDefault_decode ,
}
/* No side effect */
